server:
  8081
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/school
    username: root
    password: 123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
